---
title: "Notre système de revue de paquets en revue : présenter et analyser rOpenSci onboarding"
author: "Maëlle Salmon"
output: pdf_document
---

rOpenSci

54000 Nancy

```maelle.salmon@yahoo.se```


Mots clefs : assurance qualité, revue par les pairs, git, GitHub, API, JSON, tidytext, analyse de sentiment, jq, jqr, GraphQL.

rOpenSci est une communauté de chercheurs et de développeurs informatiques collaborant pour créer des paquets R pour soutenir la science ouverte et reproductible. Certains de ces paquets sont créés et maintenus par le personnel de rOpenSci, d'autres par des volontaires. Pour assurer la qualité de tous les paquets, rOpenSci a un système de revue des paquets par des pairs [1]. Ce système est transparent et accessible sur GitHub.

Dans cet oral, ce système sera présenté. Des analyses des revues seront présentées grâce à des outils R d'extraction de données git et GitHub [1-6] et à des outils R d'analyse de code et de texte [7-8]. Venez écouter cet oral si vous êtes curieux de la revue de paquets par les pairs, ou que vous vous demandez comment interagir avec l'API V4 de GitHub, comment dompter du JSON, visualiser un historique git, compter des lignes de code, et résumer le texte d'issues GitHub ! Vous apprendrez sûrement quelque chose.

## Références

[1] PLACEHOLDER

[2] Scott Chamberlain (2018). ghql: General Purpose GraphQL Client. R package
  version 0.0.4.9210. https://github.com/ropensci/ghql

[3] Rich FitzJohn, Jeroen Ooms, Scott Chamberlain and Stefan Milton Bache
  (2017). jqr: Client for 'jq', a 'JSON' Processor. R package version
  1.0.0. https://CRAN.R-project.org/package=jqr
  
[4] Maëlle Salmon and Scott Chamberlain (2018). ghrecipes: Provides some helper
  functions for using the GitHub V4 API. R package version 0.1.0. https://github.com/ropenscilabs/ghrecipes
  
[5] Widgren, S., et al. (2018) git2r: Provides Access to Git Repositories. R
  package version 0.21.0. URL https://CRAN.R-project.org/package=git2r.
  
[6] Lorenz Walthert (2018). gitsum: Parse and summarize git repositories. R
  package version 0.0.9001.
  
[7] Bob Rudis and Al Danial (2018). cloc: Count Lines of Code, Comments and
  Whitespace in Source Files and Archives. R package version 0.1.0.

[8] Silge J and Robinson D (2016). “tidytext: Text Mining and Analysis Using
Tidy Data Principles in R.” _JOSS_, *1*(3). doi: 10.21105/joss.00037 (URL:
http://doi.org/10.21105/joss.00037), <URL:
http://dx.doi.org/10.21105/joss.00037>.

[9] Rinker, T. W. (2018). sentimentr: Calculate Text Polarity Sentiment
  version 2.2.3. http://github.com/trinker/sentimentr
  

