---
title: "Capturez votre écran depuis R !"
author: "Maëlle Salmon"
output: pdf_document
---

rOpenSci

54000 Nancy

```maelle.salmon@yahoo.se```



Mots clefs : RMarkdown, manipulation d'images, JavaScript, PhantomJS, webshot, magick.


Avez-vous déjà voulu montrer votre beau site internet ou votre magnifique app Shiny dans des diapos ? Avez-vous capturé l'écran, enregistré puis rogné et embelli l'image, avant d'insérer à la main sa localisation dans la source de vos diapos ? Puis réalisé que ce serait bien de changer l'exemple... et tout recommencé ? Simplifiez-vous la vie et créez vos captures grâce aux paquets `webshot`[1] et `magick`[2] ! Reproducibilité et moindre effort ! Quelques commandes R à connaître et écrire dans votre source RMarkdown, et zoup, vous pourrez capturer votre écran à tout va ! Ce lightning talk présentera ces outils avec des exemples pratiques.

## Références
[1] Winston Chang (2017). webshot: Take Screenshots of Web Pages. R package
  version 0.5.0. https://CRAN.R-project.org/package=webshot

[2] Jeroen Ooms (2018). magick: Advanced Graphics and Image-Processing in R.
  R package version 1.8. https://CRAN.R-project.org/package=magick
